{% set version = "3.0.0" %}

package:
  name: pytest-benchmark
  version: {{ version }}

source:
  fn: pytest-benchmark-{{ version }}.zip
  url: https://pypi.python.org/packages/source/p/pytest-benchmark/pytest-benchmark-{{ version }}.zip
  md5: f8ab8e438f039366e3765168ad831b4c

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - setuptools
    - pytest >=2.6
    - statistics  # [py<34]

  run:
    - python
    - setuptools
    - pytest >=2.6
    - statistics  # [py<34]

test:
  imports:
    - pytest_benchmark
  commands:
    - "py.test --traceconfig | grep pytest-benchmark-{{version}}"

about:
  home: https://github.com/ionelmc/pytest-benchmark
  license: BSD 2-clause
  summary: "A py.test fixture for benchmarking code"

extra:
    recipe-maintainers:
        - juanlu001
