{% set version = "3.2.2" %}

package:
  name: pytest-benchmark
  version: {{ version }}

source:
  fn: pytest-benchmark-{{ version }}.zip
  url: https://pypi.python.org/packages/source/p/pytest-benchmark/pytest-benchmark-{{ version }}.tar.gz
  md5: cec1d1d259b9869ac306f91936f9607508a119c34f21cca79d50521bc29bf980

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    #- setuptools
    - pytest >=2.6
    - statistics  # [py<34]

test:
  imports:
    - pytest_benchmark
  commands:
    - "py.test --traceconfig | grep pytest-benchmark-{{version}}"

about:
  home: https://github.com/ionelmc/pytest-benchmark
  license: BSD 2-clause
  summary: "A py.test fixture for benchmarking code"

extra:
    recipe-maintainers:
        - juanlu001
        - esloch
