{% set version = "3.2.3" %}

package:
  name: pytest-benchmark
  version: {{ version }}

source:
  fn: pytest-benchmark-{{ version }}.zip
  url: https://pypi.python.org/packages/source/p/pytest-benchmark/pytest-benchmark-{{ version }}.tar.gz
  sha256: ad4314d093a3089701b24c80a05121994c7765ce373478c8f4ba8d23c9ba9528

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - pytest >=2.6
    - py-cpuinfo

test:
  imports:
    - pytest_benchmark
  commands:
    - "py.test --traceconfig | grep pytest-benchmark-{{version}}"

about:
  home: https://github.com/ionelmc/pytest-benchmark
  license: BSD-2-Clause
  license_file: LICENSE
  summary: "A py.test fixture for benchmarking code"

extra:
  recipe-maintainers:
    - astrojuanlu
    - esloch
